
# nome = input("qual o seu nome? ")
# print("prazer te conhecer {:-^20}?".format(nome))
# v1 = int(input('escreva um valor a: '))
# v2 = int(input('escreva um valor b: '))
# n = v1 + v2
# print('a soma de {}, mais {}, é igual à: {}!'.format(v1,v2,n))
# a = input('digita algo: ')
# b = type(a)
# c = a.isspace()
# d = a.isnumeric()
# e = a.isalpha()
# f = a.isalnum()
# g = a.isupper()
# h = a.islower()
# i = a.istitle()
# print('o tipo desse "algo" é: {}'.format(b))
# print('esse algo é um espaço? {}'.format(c))
# print('esse algo é um número? {}'.format(d))
# print('esse algo é alfabetico? {}'.format(e))
# print('esse algo é alfa-numerico? {}'.format(f))
# print('esse algo está em maiúsculo? {}'.format(g))
# print('esse algo está em minúsculo? {}'.format(h))
# print('esse algo está capitalizada? {}'.format(i))